apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserListManage
  labels:
    app: UserListManage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserListManage
  template:
    metadata:
      labels:
        app: UserListManage
    spec:
      containers:
        - name: UserListManage
          image: username/UserListManage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5